# Generated by Django 2.2.19 on 2022-12-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_cliente_empresa_especie_porte'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='porte',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='porte',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='porte',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='porte',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, verbose_name='Twitter'),
        ),
    ]
